/*
 * PolicyProvisionerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2016
 */
package com.veritas.netbackup.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Client 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5439415455547249435L;
    private String extInfo;
    private String hostname;
    private String os;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extInfo")
    public String getExtInfo ( ) { 
        return this.extInfo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extInfo")
    public void setExtInfo (String value) { 
        this.extInfo = value;
        notifyObservers(this.extInfo);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hostname")
    public String getHostname ( ) { 
        return this.hostname;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hostname")
    public void setHostname (String value) { 
        this.hostname = value;
        notifyObservers(this.hostname);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("os")
    public String getOs ( ) { 
        return this.os;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("os")
    public void setOs (String value) { 
        this.os = value;
        notifyObservers(this.os);
    }
 
}
 