/*
 * PolicyProvisionerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2016
 */
package com.veritas.netbackup.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Day 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4831223493722664080L;
    private int durationSeconds;
    private int openSeconds;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("durationSeconds")
    public int getDurationSeconds ( ) { 
        return this.durationSeconds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("durationSeconds")
    public void setDurationSeconds (int value) { 
        this.durationSeconds = value;
        notifyObservers(this.durationSeconds);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("openSeconds")
    public int getOpenSeconds ( ) { 
        return this.openSeconds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("openSeconds")
    public void setOpenSeconds (int value) { 
        this.openSeconds = value;
        notifyObservers(this.openSeconds);
    }
 
}
 