/*
 * PolicyProvisionerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2016
 */
package com.veritas.netbackup.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PoliciesResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5382293164497018000L;
    private LinkedHashMap<String, Object> links;
    private String policyName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("_links")
    public LinkedHashMap<String, Object> getLinks ( ) { 
        return this.links;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("_links")
    public void setLinks (LinkedHashMap<String, Object> value) { 
        this.links = value;
        notifyObservers(this.links);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("policyName")
    public String getPolicyName ( ) { 
        return this.policyName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("policyName")
    public void setPolicyName (String value) { 
        this.policyName = value;
        notifyObservers(this.policyName);
    }
 
}
 