/*
 * PolicyProvisionerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2016
 */
package com.veritas.netbackup.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PoliciesResponse1 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5616547184439881502L;
    private List<LinkedHashMap<String, Object>> policyList;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("policy_list")
    public List<LinkedHashMap<String, Object>> getPolicyList ( ) { 
        return this.policyList;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("policy_list")
    public void setPolicyList (List<LinkedHashMap<String, Object>> value) { 
        this.policyList = value;
        notifyObservers(this.policyList);
    }
 
}
 