/*
 * PolicyProvisionerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2016
 */
package com.veritas.netbackup.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Policy 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5227130847904562578L;
    private Attributes attributes;
    private List<Client> clients;
    private List<String> includes;
    private String policyName;
    private List<Schedule> schedules;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("attributes")
    public Attributes getAttributes ( ) { 
        return this.attributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("attributes")
    public void setAttributes (Attributes value) { 
        this.attributes = value;
        notifyObservers(this.attributes);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("clients")
    public List<Client> getClients ( ) { 
        return this.clients;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("clients")
    public void setClients (List<Client> value) { 
        this.clients = value;
        notifyObservers(this.clients);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("includes")
    public List<String> getIncludes ( ) { 
        return this.includes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("includes")
    public void setIncludes (List<String> value) { 
        this.includes = value;
        notifyObservers(this.includes);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("policyName")
    public String getPolicyName ( ) { 
        return this.policyName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("policyName")
    public void setPolicyName (String value) { 
        this.policyName = value;
        notifyObservers(this.policyName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("schedules")
    public List<Schedule> getSchedules ( ) { 
        return this.schedules;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("schedules")
    public void setSchedules (List<Schedule> value) { 
        this.schedules = value;
        notifyObservers(this.schedules);
    }
 
}
 