/*
 * PolicyProvisionerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2016
 */
package com.veritas.netbackup.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Schedule 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5699654785599747708L;
    private String altReadHost;
    private List<Day> days;
    private boolean fastRecovery;
    private int frequencySeconds;
    private String incrementalType;
    private int maxFragSizeMb;
    private int numberOfCopies;
    private int retentionLevel;
    private String scheduleType;
    private String scheuduleName;
    private boolean synthetic;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("altReadHost")
    public String getAltReadHost ( ) { 
        return this.altReadHost;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("altReadHost")
    public void setAltReadHost (String value) { 
        this.altReadHost = value;
        notifyObservers(this.altReadHost);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("days")
    public List<Day> getDays ( ) { 
        return this.days;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("days")
    public void setDays (List<Day> value) { 
        this.days = value;
        notifyObservers(this.days);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fastRecovery")
    public boolean getFastRecovery ( ) { 
        return this.fastRecovery;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fastRecovery")
    public void setFastRecovery (boolean value) { 
        this.fastRecovery = value;
        notifyObservers(this.fastRecovery);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("frequencySeconds")
    public int getFrequencySeconds ( ) { 
        return this.frequencySeconds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("frequencySeconds")
    public void setFrequencySeconds (int value) { 
        this.frequencySeconds = value;
        notifyObservers(this.frequencySeconds);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("incrementalType")
    public String getIncrementalType ( ) { 
        return this.incrementalType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("incrementalType")
    public void setIncrementalType (String value) { 
        this.incrementalType = value;
        notifyObservers(this.incrementalType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("maxFragSizeMb")
    public int getMaxFragSizeMb ( ) { 
        return this.maxFragSizeMb;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("maxFragSizeMb")
    public void setMaxFragSizeMb (int value) { 
        this.maxFragSizeMb = value;
        notifyObservers(this.maxFragSizeMb);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("numberOfCopies")
    public int getNumberOfCopies ( ) { 
        return this.numberOfCopies;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("numberOfCopies")
    public void setNumberOfCopies (int value) { 
        this.numberOfCopies = value;
        notifyObservers(this.numberOfCopies);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("retentionLevel")
    public int getRetentionLevel ( ) { 
        return this.retentionLevel;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("retentionLevel")
    public void setRetentionLevel (int value) { 
        this.retentionLevel = value;
        notifyObservers(this.retentionLevel);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("scheduleType")
    public String getScheduleType ( ) { 
        return this.scheduleType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("scheduleType")
    public void setScheduleType (String value) { 
        this.scheduleType = value;
        notifyObservers(this.scheduleType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("scheuduleName")
    public String getScheuduleName ( ) { 
        return this.scheuduleName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("scheuduleName")
    public void setScheuduleName (String value) { 
        this.scheuduleName = value;
        notifyObservers(this.scheuduleName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("synthetic")
    public boolean getSynthetic ( ) { 
        return this.synthetic;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("synthetic")
    public void setSynthetic (boolean value) { 
        this.synthetic = value;
        notifyObservers(this.synthetic);
    }
 
}
 